export const HERO_HEADING_DURATION = 1;
export const HERO_HEADING_INITIAL_SCALE = 0.9;
export const HERO_HEADING_FINAL_SCALE = 1;
export const HERO_HEADING_INITIAL_OPACITY = 0;
export const HERO_HEADING_FINAL_OPACITY = 1;